package platform

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"sort"
	"strings"
	"time"
)

var ErrConflict=errors.New("resource already exists")
func cleanHandle(v string) string { return strings.ToLower(strings.Trim(strings.TrimSpace(v),"@")) }
func contentKey(kind,id string) string { return kind+":"+id }

func (s *Store) CreateUser(email,handle,name string)(User,error){
	s.mu.Lock(); defer s.mu.Unlock(); handle=cleanHandle(handle); email=strings.ToLower(strings.TrimSpace(email)); if email==""||handle==""{return User{},errors.New("email and handle are required")}
	for _,u:=range s.state.Users{if u.Email==email||u.Handle==handle{return User{},ErrConflict}}
	u:=User{ID:newID("usr"),Email:email,Handle:handle,DisplayName:strings.TrimSpace(name),Role:"creator",CreatedAt:time.Now().UTC()}; if u.DisplayName==""{u.DisplayName=handle}; s.state.Users[u.ID]=u
	if err:=s.persistLocked(context.Background(),"account.created",u);err!=nil{return User{},err}; return u,nil
}
func(s *Store) Profile(handle string)(User,error){s.mu.RLock();defer s.mu.RUnlock();handle=cleanHandle(handle);for _,u:=range s.state.Users{if u.Handle==handle{return u,nil}};return User{},ErrNotFound}
func(s *Store) CreateSession(email string)(Session,string,error){
	s.mu.Lock();defer s.mu.Unlock();email=strings.ToLower(strings.TrimSpace(email));var user User;found:=false;for _,u:=range s.state.Users{if u.Email==email{user=u;found=true;break}};if !found{return Session{},"",ErrNotFound}
	token:=newID("ngg");sum:=sha256.Sum256([]byte(token));ss:=Session{ID:newID("ses"),UserID:user.ID,TokenHash:hex.EncodeToString(sum[:]),CreatedAt:time.Now().UTC(),ExpiresAt:time.Now().UTC().Add(30*24*time.Hour)};s.state.Sessions[ss.ID]=ss
	if err:=s.persistLocked(context.Background(),"session.created",map[string]string{"id":ss.ID,"userId":user.ID});err!=nil{return Session{},"",err};return ss,token,nil
}
func(s *Store) CreateProject(ownerID,kind,slug,title,description string,tags []string)(Project,error){
	s.mu.Lock();defer s.mu.Unlock();if _,ok:=s.state.Users[ownerID];!ok{return Project{},ErrNotFound};kind=strings.ToLower(strings.TrimSpace(kind));if kind!="game"&&kind!="video"{return Project{},errors.New("kind must be game or video")};slug=cleanHandle(slug);if slug==""||strings.TrimSpace(title)==""{return Project{},errors.New("slug and title are required")};for _,p:=range s.state.Projects{if p.Slug==slug{return Project{},ErrConflict}}
	now:=time.Now().UTC();p:=Project{ID:newID("prj"),OwnerID:ownerID,Kind:kind,Slug:slug,Title:strings.TrimSpace(title),Description:strings.TrimSpace(description),Status:"draft",Tags:tags,Members:map[string]string{ownerID:"owner"},CreatedAt:now,UpdatedAt:now};s.state.Projects[p.ID]=p;if err:=s.persistLocked(context.Background(),"project.created",p);err!=nil{return Project{},err};return p,nil
}
func(s *Store) Project(id string)(Project,error){s.mu.RLock();defer s.mu.RUnlock();p,ok:=s.state.Projects[id];if !ok{return Project{},ErrNotFound};return p,nil}
func(s *Store) AddProjectMember(projectID,userID,role string)(Project,error){s.mu.Lock();defer s.mu.Unlock();p,ok:=s.state.Projects[projectID];if !ok{return Project{},ErrNotFound};if _,ok:=s.state.Users[userID];!ok{return Project{},ErrNotFound};if p.Members==nil{p.Members=map[string]string{}};p.Members[userID]=strings.TrimSpace(role);p.UpdatedAt=time.Now().UTC();s.state.Projects[p.ID]=p;if err:=s.persistLocked(context.Background(),"project.member_added",map[string]string{"projectId":projectID,"userId":userID,"role":role});err!=nil{return Project{},err};return p,nil}
func(s *Store) SubmitProject(id string)(Project,error){s.mu.Lock();defer s.mu.Unlock();p,ok:=s.state.Projects[id];if !ok{return Project{},ErrNotFound};p.Status="submitted";p.UpdatedAt=time.Now().UTC();s.state.Projects[id]=p;if err:=s.persistLocked(context.Background(),"project.submitted",p);err!=nil{return Project{},err};return p,nil}

func(s *Store) CreateUpload(projectID,kind,contentType string,size int64)(Upload,error){s.mu.Lock();defer s.mu.Unlock();if _,ok:=s.state.Projects[projectID];!ok{return Upload{},ErrNotFound};id:=newID("upl");objectKey:="projects/"+projectID+"/"+id;u:=Upload{ID:id,ProjectID:projectID,Kind:kind,ObjectKey:objectKey,UploadURL:"/api/v1/uploads/"+id+"/data",Status:"pending",ContentType:contentType,Size:size,CreatedAt:time.Now().UTC()};s.state.Uploads[id]=u;if err:=s.persistLocked(context.Background(),"upload.created",u);err!=nil{return Upload{},err};return u,nil}
func(s *Store) CompleteUpload(id string)(Upload,error){s.mu.Lock();defer s.mu.Unlock();u,ok:=s.state.Uploads[id];if !ok{return Upload{},ErrNotFound};u.Status="ready";s.state.Uploads[id]=u;if err:=s.persistLocked(context.Background(),"upload.completed",u);err!=nil{return Upload{},err};return u,nil}
func(s *Store) CreateRelease(projectID,uploadID,version string)(Release,error){s.mu.Lock();defer s.mu.Unlock();p,ok:=s.state.Projects[projectID];if !ok{return Release{},ErrNotFound};u,ok:=s.state.Uploads[uploadID];if !ok||u.ProjectID!=projectID||u.Status!="ready"{return Release{},errors.New("a completed project upload is required")};status:="published";player:="/play/"+p.Slug;if p.Kind=="video"{status="processing";player="/watch/"+p.Slug};r:=Release{ID:newID("rel"),ProjectID:projectID,Version:version,ObjectKey:u.ObjectKey,PlayerURL:player,Status:status,CreatedAt:time.Now().UTC()};s.state.Releases[r.ID]=r;p.Status=status;p.UpdatedAt=time.Now().UTC();s.state.Projects[p.ID]=p;if err:=s.persistLocked(context.Background(),"release.created",r);err!=nil{return Release{},err};return r,nil}
func(s *Store) UpdateRelease(id,status,playerURL string)(Release,error){s.mu.Lock();defer s.mu.Unlock();r,ok:=s.state.Releases[id];if !ok{return Release{},ErrNotFound};switch status{case "processing","published","failed":default:return Release{},errors.New("invalid release status")};r.Status=status;if strings.TrimSpace(playerURL)!=""{r.PlayerURL=playerURL};s.state.Releases[id]=r;p:=s.state.Projects[r.ProjectID];p.Status=status;p.UpdatedAt=time.Now().UTC();s.state.Projects[p.ID]=p;if err:=s.persistLocked(context.Background(),"release.status_changed",map[string]string{"releaseId":id,"status":status});err!=nil{return Release{},err};return r,nil}

func(s *Store) Comments(kind,id string)[]ContentComment{s.mu.RLock();defer s.mu.RUnlock();return append([]ContentComment(nil),s.state.ContentComments[contentKey(kind,id)]...)}
func(s *Store) AddContentComment(kind,id,author,body string)(ContentComment,error){s.mu.Lock();defer s.mu.Unlock();body=strings.TrimSpace(body);if body==""||len(body)>4000{return ContentComment{},errors.New("comment must contain 1-4000 characters")};c:=ContentComment{ID:newID("com"),ContentType:kind,ContentID:id,AuthorID:author,Body:body,CreatedAt:time.Now().UTC()};key:=contentKey(kind,id);s.state.ContentComments[key]=append([]ContentComment{c},s.state.ContentComments[key]...);if err:=s.persistLocked(context.Background(),"content.commented",c);err!=nil{return ContentComment{},err};return c,nil}
func(s *Store) Rate(kind,id,user string,value int)(float64,error){if value<1||value>5{return 0,errors.New("rating must be between 1 and 5")};s.mu.Lock();defer s.mu.Unlock();key:=contentKey(kind,id);if s.state.Ratings[key]==nil{s.state.Ratings[key]=map[string]int{}};s.state.Ratings[key][user]=value;total:=0;for _,v:=range s.state.Ratings[key]{total+=v};avg:=float64(total)/float64(len(s.state.Ratings[key]));if err:=s.persistLocked(context.Background(),"content.rated",map[string]any{"content":key,"userId":user,"rating":value});err!=nil{return 0,err};return avg,nil}
func(s *Store) Favorite(kind,id,user string)(bool,error){s.mu.Lock();defer s.mu.Unlock();key:=contentKey(kind,id);if s.state.Favorites[user]==nil{s.state.Favorites[user]=map[string]bool{}};s.state.Favorites[user][key]=!s.state.Favorites[user][key];v:=s.state.Favorites[user][key];if err:=s.persistLocked(context.Background(),"content.favorited",map[string]any{"content":key,"userId":user,"favorite":v});err!=nil{return false,err};return v,nil}

func(s *Store) Categories()[]ForumCategory{s.mu.RLock();defer s.mu.RUnlock();out:=make([]ForumCategory,0,len(s.state.ForumCategories));for _,v:=range s.state.ForumCategories{out=append(out,v)};sort.Slice(out,func(i,j int)bool{return out[i].Name<out[j].Name});return out}
func(s *Store) CreateThread(category,author,title,body string)(ForumThread,error){s.mu.Lock();defer s.mu.Unlock();if _,ok:=s.state.ForumCategories[category];!ok{return ForumThread{},ErrNotFound};if strings.TrimSpace(title)==""||strings.TrimSpace(body)==""{return ForumThread{},errors.New("title and body are required")};now:=time.Now().UTC();t:=ForumThread{ID:newID("thr"),CategoryID:category,AuthorID:author,Title:strings.TrimSpace(title),CreatedAt:now,UpdatedAt:now};s.state.ForumThreads[t.ID]=t;p:=ForumPost{ID:newID("post"),ThreadID:t.ID,AuthorID:author,Body:strings.TrimSpace(body),CreatedAt:now,UpdatedAt:now};s.state.ForumPosts[t.ID]=[]ForumPost{p};if err:=s.persistLocked(context.Background(),"forum.thread_created",t);err!=nil{return ForumThread{},err};return t,nil}
func(s *Store) Thread(id string)(ForumThread,[]ForumPost,error){s.mu.RLock();defer s.mu.RUnlock();t,ok:=s.state.ForumThreads[id];if !ok{return ForumThread{},nil,ErrNotFound};return t,append([]ForumPost(nil),s.state.ForumPosts[id]...),nil}
func(s *Store) AddPost(thread,author,body string)(ForumPost,error){s.mu.Lock();defer s.mu.Unlock();t,ok:=s.state.ForumThreads[thread];if !ok{return ForumPost{},ErrNotFound};if t.Locked{return ForumPost{},errors.New("thread is locked")};body=strings.TrimSpace(body);if body==""{return ForumPost{},errors.New("body is required")};now:=time.Now().UTC();p:=ForumPost{ID:newID("post"),ThreadID:thread,AuthorID:author,Body:body,CreatedAt:now,UpdatedAt:now};s.state.ForumPosts[thread]=append(s.state.ForumPosts[thread],p);t.UpdatedAt=now;s.state.ForumThreads[thread]=t;s.addMentionNotificationsLocked(body,author,"/forums/threads/"+thread);if err:=s.persistLocked(context.Background(),"forum.posted",p);err!=nil{return ForumPost{},err};return p,nil}
func(s *Store) addMentionNotificationsLocked(body,actor,target string){for _,field:=range strings.Fields(body){if !strings.HasPrefix(field,"@"){continue};handle:=cleanHandle(strings.Trim(field,".,:;!?"));for _,u:=range s.state.Users{if u.Handle==handle&&u.ID!=actor{n:=Notification{ID:newID("ntf"),UserID:u.ID,Kind:"mention",Message:"You were mentioned in the forum",URL:target,CreatedAt:time.Now().UTC()};s.state.Notifications[u.ID]=append([]Notification{n},s.state.Notifications[u.ID]...)}}}}
func(s *Store) UserNotifications(id string)[]Notification{s.mu.RLock();defer s.mu.RUnlock();return append([]Notification(nil),s.state.Notifications[id]...)}

func(s *Store) CreateReport(reporter,targetType,targetID,reason string)(Report,error){s.mu.Lock();defer s.mu.Unlock();if strings.TrimSpace(reason)==""{return Report{},errors.New("reason is required")};r:=Report{ID:newID("rpt"),ReporterID:reporter,TargetType:targetType,TargetID:targetID,Reason:reason,Status:"open",CreatedAt:time.Now().UTC()};s.state.CommunityReports[r.ID]=r;if err:=s.persistLocked(context.Background(),"moderation.reported",r);err!=nil{return Report{},err};return r,nil}
func(s *Store) ModerationQueue()[]Report{s.mu.RLock();defer s.mu.RUnlock();out:=[]Report{};for _,r:=range s.state.CommunityReports{if r.Status=="open"{out=append(out,r)}};return out}
func(s *Store) Moderate(reportID,moderator,action,note string)(ModerationAction,error){s.mu.Lock();defer s.mu.Unlock();r,ok:=s.state.CommunityReports[reportID];if !ok{return ModerationAction{},ErrNotFound};r.Status="resolved";s.state.CommunityReports[reportID]=r;a:=ModerationAction{ID:newID("mod"),ModeratorID:moderator,ReportID:reportID,Action:action,Note:note,CreatedAt:time.Now().UTC()};s.state.ModerationActions=append(s.state.ModerationActions,a);if err:=s.persistLocked(context.Background(),"moderation.actioned",a);err!=nil{return ModerationAction{},err};return a,nil}

func(s *Store) UnlockAchievement(game,user,id,name,description string,points int)(AchievementUnlock,error){s.mu.Lock();defer s.mu.Unlock();key:=game+":"+id;a:=Achievement{ID:key,GameID:game,Name:name,Description:description,Points:points};s.state.Achievements[key]=a;for _,u:=range s.state.Unlocks{if u.AchievementID==key&&u.UserID==user{return u,nil}};u:=AchievementUnlock{AchievementID:key,UserID:user,UnlockedAt:time.Now().UTC()};s.state.Unlocks=append(s.state.Unlocks,u);if err:=s.persistLocked(context.Background(),"sdk.achievement_unlocked",u);err!=nil{return AchievementUnlock{},err};return u,nil}
func(s *Store) SubmitScore(game,board,user string,score int64,metadata json.RawMessage)(LeaderboardScore,error){s.mu.Lock();defer s.mu.Unlock();v:=LeaderboardScore{GameID:game,Board:board,UserID:user,Score:score,Metadata:metadata,SubmittedAt:time.Now().UTC()};s.state.Scores=append(s.state.Scores,v);if err:=s.persistLocked(context.Background(),"sdk.score_submitted",v);err!=nil{return LeaderboardScore{},err};return v,nil}
func(s *Store) Leaderboard(game,board string)[]LeaderboardScore{s.mu.RLock();defer s.mu.RUnlock();out:=[]LeaderboardScore{};for _,v:=range s.state.Scores{if v.GameID==game&&v.Board==board{out=append(out,v)}};sort.Slice(out,func(i,j int)bool{return out[i].Score>out[j].Score});if len(out)>100{out=out[:100]};return out}
func(s *Store) PutSave(game,user,slot string,data json.RawMessage,version int)(CloudSave,error){s.mu.Lock();defer s.mu.Unlock();key:=game+":"+user+":"+slot;old,ok:=s.state.Saves[key];if ok&&version!=old.Version{return CloudSave{},ErrConflict};v:=CloudSave{GameID:game,UserID:user,Slot:slot,Data:data,Version:version+1,UpdatedAt:time.Now().UTC()};s.state.Saves[key]=v;if err:=s.persistLocked(context.Background(),"sdk.save_written",map[string]any{"gameId":game,"userId":user,"slot":slot,"version":v.Version});err!=nil{return CloudSave{},err};return v,nil}
func(s *Store) GetSave(game,user,slot string)(CloudSave,error){s.mu.RLock();defer s.mu.RUnlock();v,ok:=s.state.Saves[game+":"+user+":"+slot];if !ok{return CloudSave{},ErrNotFound};return v,nil}

func(s *Store) ArcadeGames()[]ArcadeGame{s.mu.RLock();defer s.mu.RUnlock();out:=make([]ArcadeGame,0,len(s.state.ArcadeGames));for _,v:=range s.state.ArcadeGames{out=append(out,v)};sort.Slice(out,func(i,j int)bool{return out[i].Name<out[j].Name});return out}
func initialRoomState(game string)json.RawMessage{if game=="tic-tac-toe"{return json.RawMessage(`{"board":["","","","","","","","",""]}`)};if game=="four-in-a-row"{return json.RawMessage(`{"board":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}`)};return json.RawMessage(`{"moves":[]}`)}
func(s *Store) CreateRoom(game,host string)(ArcadeRoom,error){s.mu.Lock();defer s.mu.Unlock();g,ok:=s.state.ArcadeGames[game];if !ok{return ArcadeRoom{},ErrNotFound};now:=time.Now().UTC();status:="waiting";if g.MinPlayers<=1{status="playing"};r:=ArcadeRoom{ID:newID("room"),GameID:game,HostID:host,Status:status,Players:[]string{host},State:initialRoomState(game),Version:1,CreatedAt:now,UpdatedAt:now};s.state.ArcadeRooms[r.ID]=r;if err:=s.persistLocked(context.Background(),"arcade.room_created",r);err!=nil{return ArcadeRoom{},err};return r,nil}
func(s *Store) Room(id string)(ArcadeRoom,error){s.mu.RLock();defer s.mu.RUnlock();r,ok:=s.state.ArcadeRooms[id];if !ok{return ArcadeRoom{},ErrNotFound};return r,nil}
func(s *Store) JoinRoom(id,user string)(ArcadeRoom,error){s.mu.Lock();defer s.mu.Unlock();r,ok:=s.state.ArcadeRooms[id];if !ok{return ArcadeRoom{},ErrNotFound};g:=s.state.ArcadeGames[r.GameID];for _,p:=range r.Players{if p==user{return r,nil}};if len(r.Players)>=g.MaxPlayers{return ArcadeRoom{},ErrConflict};r.Players=append(r.Players,user);if len(r.Players)>=g.MinPlayers{r.Status="playing"};r.Version++;r.UpdatedAt=time.Now().UTC();s.state.ArcadeRooms[id]=r;if err:=s.persistLocked(context.Background(),"arcade.room_joined",map[string]string{"roomId":id,"userId":user});err!=nil{return ArcadeRoom{},err};return r,nil}
func(s *Store) Move(id,user string,expected int,move json.RawMessage)(ArcadeRoom,error){s.mu.Lock();defer s.mu.Unlock();r,ok:=s.state.ArcadeRooms[id];if !ok{return ArcadeRoom{},ErrNotFound};if r.Status!="playing"{return ArcadeRoom{},errors.New("room is not ready")};if expected!=r.Version{return ArcadeRoom{},ErrConflict};allowed:=false;for _,p:=range r.Players{if p==user{allowed=true}};if !allowed{return ArcadeRoom{},errors.New("player is not in this room")};var state map[string]any;if err:=json.Unmarshal(r.State,&state);err!=nil{return ArcadeRoom{},err};moves,_:=state["moves"].([]any);var decoded any;if err:=json.Unmarshal(move,&decoded);err!=nil{return ArcadeRoom{},err};moves=append(moves,map[string]any{"player":user,"move":decoded});state["moves"]=moves;r.State,_=json.Marshal(state);r.Version++;r.UpdatedAt=time.Now().UTC();s.state.ArcadeRooms[id]=r;if err:=s.persistLocked(context.Background(),"arcade.move",map[string]any{"roomId":id,"userId":user,"version":r.Version});err!=nil{return ArcadeRoom{},err};return r,nil}
