import { For, createSignal } from "solid-js";
import * as stylex from "@stylexjs/stylex";
import { s } from "./styles.stylex";

type ArcadeGame = { id:string; name:string; description:string; minPlayers:number; maxPlayers:number };
type ForumCategory = { id:string; name:string; description:string };
const getJSON = async <T,>(url:string):Promise<T> => { const response=await fetch(url); if(!response.ok) throw new Error("Request failed"); return response.json() as Promise<T>; };

function Shell(props:{eyebrow:string;title:string;lead:string;children?:unknown}) {
  return <main {...stylex.attrs(s.portal)}><section {...stylex.attrs(s.hero)}><div {...stylex.attrs(s.eyebrow)}>{props.eyebrow}</div><h1 {...stylex.attrs(s.portalTitle)}>{props.title}</h1><p {...stylex.attrs(s.portalLead)}>{props.lead}</p><div {...stylex.attrs(s.portalActions)}><a href="/submit" {...stylex.attrs(s.primary)} style={{width:"auto"}}>Publish your work</a><a href="/forums" {...stylex.attrs(s.secondary)}>Meet creators</a></div></section>{props.children as never}</main>;
}

function Discover(){return <Shell eyebrow="PLAY · CREATE · SHARE" title="The front page for browser creativity." lead="Play games and watch creator videos, then rate, favorite, discuss, and follow the people who made them."><div {...stylex.attrs(s.portalGrid)}>{[["🎮","Games","Instant HTML5 and WebAssembly games in a focused sandbox."],["▶","Videos","Adaptive streaming, captions, comments, and creator credits."],["✦","Community","Profiles, forums, playlists, achievements, and friendly competition."]].map(x=><article {...stylex.attrs(s.portalCard)}><div {...stylex.attrs(s.gameGlyph)}>{x[0]}</div><h2 {...stylex.attrs(s.portalCardTitle)}>{x[1]}</h2><p {...stylex.attrs(s.portalCopy)}>{x[2]}</p></article>)}</div></Shell>}

function Arcade(){const [games,setGames]=createSignal<ArcadeGame[]>([]);void getJSON<ArcadeGame[]>("/api/v1/arcade/games").then(setGames);return <Shell eyebrow="NGG ARCADE" title="Quick games. Real opponents." lead="Five original turn-based games share one authoritative room protocol, so a match works anywhere NGG does."><div {...stylex.attrs(s.portalGrid)}><For each={games()}>{game=><article {...stylex.attrs(s.portalCard)}><div {...stylex.attrs(s.gameGlyph)}>{game.name.slice(0,2).toUpperCase()}</div><h2 {...stylex.attrs(s.portalCardTitle)}>{game.name}</h2><p {...stylex.attrs(s.portalCopy)}>{game.description} · {game.minPlayers}–{game.maxPlayers} players</p><button {...stylex.attrs(s.secondary)}>Create room</button></article>}</For></div></Shell>}

function Forums(){const [categories,setCategories]=createSignal<ForumCategory[]>([]);void getJSON<ForumCategory[]>("/api/v1/forums/categories").then(setCategories);return <Shell eyebrow="COMMUNITY" title="Talk games. Make strange things together." lead="Public discussions, creator collaboration, mentions, notifications, and moderation are built into the same platform."><div {...stylex.attrs(s.portalGrid)}><For each={categories()}>{category=><article {...stylex.attrs(s.portalCard)}><h2 {...stylex.attrs(s.portalCardTitle)}>{category.name}</h2><p {...stylex.attrs(s.portalCopy)}>{category.description}</p><a href={`/forums/${category.id}`} {...stylex.attrs(s.secondary)}>Open forum</a></article>}</For></div></Shell>}

function Account(){const [status,setStatus]=createSignal("");let email!:HTMLInputElement,handle!:HTMLInputElement,name!:HTMLInputElement;const submit=async(e:SubmitEvent)=>{e.preventDefault();const response=await fetch("/api/v1/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.value,handle:handle.value,displayName:name.value})});setStatus(response.ok?"Account created. Your public creator profile is ready.":"That email or handle is already in use.")};return <Shell eyebrow="IDENTITY" title="Claim your NGG creator profile." lead="One account owns projects, forum posts, scores, saves, playlists, and collaboration credits."><form onSubmit={submit} {...stylex.attrs(s.form)}><input ref={email} type="email" required placeholder="Email" {...stylex.attrs(s.input)}/><input ref={handle} required placeholder="Handle" {...stylex.attrs(s.input)}/><input ref={name} required placeholder="Display name" {...stylex.attrs(s.input)}/><button {...stylex.attrs(s.primary)}>Create account</button><div {...stylex.attrs(s.status)}>{status()}</div></form></Shell>}

function Submit(){return <Shell eyebrow="CREATOR PORTAL" title="Publish a game or video." lead="Create a draft, invite collaborators, upload a build, submit it for review, and publish immutable releases. Video releases enter the managed transcoding queue; games launch in an isolated player origin."><div {...stylex.attrs(s.portalGrid)}>{[["1","Create draft","Metadata, tags, credits, ownership, and collaborators."],["2","Upload","Signed direct uploads keep large media away from the Go server."],["3","Publish","Review status and immutable releases protect players and creators."]].map(x=><article {...stylex.attrs(s.portalCard)}><div {...stylex.attrs(s.gameGlyph)}>{x[0]}</div><h2 {...stylex.attrs(s.portalCardTitle)}>{x[1]}</h2><p {...stylex.attrs(s.portalCopy)}>{x[2]}</p></article>)}</div></Shell>}

export default function PortalPage(props:{path:string}){if(props.path.startsWith("/arcade"))return <Arcade/>;if(props.path.startsWith("/forums"))return <Forums/>;if(props.path.startsWith("/account"))return <Account/>;if(props.path.startsWith("/submit"))return <Submit/>;return <Discover/>}
