import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
  page: "#090c12", panel: "#111720", raised: "#171f2b", line: "#263244",
  text: "#f4f6fb", muted: "#8d99aa", yellow: "#ffd633", blue: "#56a8ff", green: "#5ce1a2", red: "#ff6b63"
});

export const s = stylex.create({
  app:{minHeight:"100vh",color:colors.text},
  top:{position:"sticky",top:0,zIndex:20,backgroundColor:"rgba(9,12,18,.94)",backdropFilter:"blur(16px)",borderBottom:"1px solid",borderColor:colors.line},
  nav:{maxWidth:"1240px",height:"66px",margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",gap:"24px"},
  logo:{fontSize:"24px",fontWeight:950,letterSpacing:"-1.5px",color:colors.yellow,whiteSpace:"nowrap"},
  mainNav:{display:{default:"flex","@media (max-width: 760px)":"none"},gap:"18px",fontSize:"14px",fontWeight:700},
  navLink:{color:colors.muted,":hover":{color:colors.text}},
  search:{marginLeft:"auto",width:{default:"260px","@media (max-width: 900px)":"160px","@media (max-width: 600px)":"120px"},border:"1px solid",borderColor:colors.line,borderRadius:"8px",backgroundColor:colors.panel,color:colors.text,padding:"10px 12px",outline:"none"},
  auth:{display:{default:"flex","@media (max-width: 600px)":"none"},gap:"10px",alignItems:"center",fontSize:"13px",fontWeight:800},
  signup:{backgroundColor:colors.yellow,color:"#171300",borderRadius:"7px",padding:"9px 12px"},
  categories:{borderTop:"1px solid",borderColor:"#151d28",overflowX:"auto"},
  categoryInner:{maxWidth:"1240px",margin:"0 auto",padding:"10px 20px",display:"flex",gap:"22px",color:colors.muted,fontSize:"12px",fontWeight:800,whiteSpace:"nowrap"},
  container:{width:"100%",maxWidth:"1240px",margin:"0 auto",padding:{default:"24px 20px 64px","@media (max-width: 700px)":"14px 12px 48px"}},
  promo:{minHeight:"112px",border:"1px solid",borderColor:"#4a3d11",borderRadius:"12px",padding:{default:"20px 28px","@media (max-width: 700px)":"18px"},display:"flex",alignItems:"center",justifyContent:"space-between",overflow:"hidden",background:"linear-gradient(110deg,#211e11,#121a25 58%,#1f1729)",position:"relative"},
  promoTitle:{fontSize:{default:"30px","@media (max-width: 700px)":"23px"},fontWeight:950,letterSpacing:"-1px",lineHeight:1,color:colors.yellow},
  promoSub:{marginTop:"8px",fontSize:"12px",fontWeight:800,letterSpacing:"1.7px",color:"#d7dce5"},
  promoArt:{display:{default:"flex","@media (max-width: 560px)":"none"},gap:"8px",alignItems:"flex-end",fontSize:"36px"},
  titleRow:{padding:"27px 0 17px",display:"flex",justifyContent:"space-between",alignItems:"end",gap:"20px"},
  eyebrow:{color:colors.blue,fontSize:"12px",fontWeight:900,textTransform:"uppercase",letterSpacing:"1.4px"},
  title:{fontSize:{default:"34px","@media (max-width: 600px)":"28px"},lineHeight:1.1,margin:"5px 0 6px",letterSpacing:"-1.2px"},
  subtitle:{color:colors.muted,fontSize:"14px"},
  livePill:{border:"1px solid",borderColor:"#325e4e",color:colors.green,backgroundColor:"#10241d",borderRadius:"999px",padding:"7px 10px",fontSize:"11px",fontWeight:900,whiteSpace:"nowrap"},
  layout:{display:"grid",gridTemplateColumns:{default:"minmax(0,3fr) minmax(270px,1fr)","@media (max-width: 860px)":"1fr"},gap:"18px",alignItems:"start"},
  panel:{backgroundColor:colors.panel,border:"1px solid",borderColor:colors.line,borderRadius:"11px",overflow:"hidden"},
  panelPad:{padding:"18px"},
  player:{backgroundColor:"#080a0f",border:"1px solid",borderColor:"#344157",borderRadius:"10px",overflow:"hidden",boxShadow:"0 18px 55px rgba(0,0,0,.32)"},
  scoreboard:{display:"grid",gridTemplateColumns:"1fr auto 1fr",alignItems:"center",padding:"12px 16px",backgroundColor:"#0e141d",borderBottom:"1px solid",borderColor:colors.line},
  team:{fontWeight:950,fontSize:"17px"},
  teamRight:{fontWeight:950,fontSize:"17px",textAlign:"right"},
  score:{fontSize:"24px",fontWeight:950,color:colors.yellow,textAlign:"center"},
  clock:{fontSize:"10px",color:colors.muted,textAlign:"center",marginTop:"2px"},
  field:{position:"relative",aspectRatio:"16 / 8",minHeight:"260px",overflow:"hidden",background:"repeating-linear-gradient(90deg,#173c30 0,#173c30 9.7%,#205040 9.8%,#205040 10%)",borderBottom:"1px solid",borderColor:colors.line},
  midfield:{position:"absolute",left:"50%",top:0,bottom:0,borderLeft:"2px solid rgba(255,255,255,.22)"},
  marker:{position:"absolute",transform:"translate(-50%,-50%)",width:"27px",height:"27px",display:"grid",placeItems:"center",borderRadius:"50%",fontSize:"15px",fontWeight:950,transition:"all 650ms cubic-bezier(.2,.8,.2,1)"},
  offense:{backgroundColor:"#f5f7fb",color:"#151b24",boxShadow:"0 2px 8px rgba(0,0,0,.35)"},
  defense:{backgroundColor:"#162236",color:"#73b7ff",border:"2px solid",borderColor:"#73b7ff"},
  ball:{position:"absolute",width:"15px",height:"10px",borderRadius:"50%",backgroundColor:"#a85d2a",border:"1px solid #f0b47c",transition:"all 650ms cubic-bezier(.2,.8,.2,1)",zIndex:3},
  situation:{position:"absolute",top:"10px",left:"10px",padding:"6px 9px",backgroundColor:"rgba(5,8,12,.82)",borderRadius:"6px",fontSize:"11px",fontWeight:900},
  controls:{display:"grid",gridTemplateColumns:{default:"minmax(0,1.2fr) minmax(230px,.8fr)","@media (max-width: 650px)":"1fr"},backgroundColor:"#0e141d"},
  playControls:{padding:"16px",borderRight:{default:"1px solid","@media (max-width: 650px)":"none"},borderColor:colors.line},
  tabs:{display:"flex",gap:"7px",marginBottom:"14px"},
  tab:{border:"1px solid",borderColor:colors.line,color:colors.muted,backgroundColor:colors.panel,borderRadius:"6px",padding:"7px 10px",fontSize:"11px",fontWeight:850,cursor:"pointer"},
  activeTab:{color:"#171300",backgroundColor:colors.yellow,borderColor:colors.yellow},
  selectRow:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"10px"},
  label:{display:"grid",gap:"5px",fontSize:"10px",fontWeight:900,textTransform:"uppercase",color:colors.muted},
  select:{width:"100%",color:colors.text,backgroundColor:colors.raised,border:"1px solid",borderColor:colors.line,borderRadius:"6px",padding:"9px"},
  playName:{fontSize:"17px",fontWeight:950,marginTop:"14px"},
  playDesc:{fontSize:"12px",color:colors.muted,margin:"4px 0 13px"},
  primary:{width:"100%",border:0,borderRadius:"7px",backgroundColor:colors.yellow,color:"#181300",fontWeight:950,padding:"12px",cursor:"pointer",":hover":{backgroundColor:"#ffe467"}},
  recent:{padding:"16px"},
  sectionLabel:{margin:"0 0 12px",fontSize:"11px",letterSpacing:"1.4px",fontWeight:950,color:colors.muted},
  playItem:{display:"flex",justifyContent:"space-between",gap:"10px",padding:"9px 0",borderBottom:"1px solid",borderColor:"#202b3a",fontSize:"11px"},
  card:{backgroundColor:colors.panel,border:"1px solid",borderColor:colors.line,borderRadius:"10px",overflow:"hidden"},
  sticky:{position:{default:"sticky","@media (max-width: 860px)":"static"},top:"118px",display:"grid",gap:"14px"},
  cover:{height:"146px",display:"grid",placeItems:"center",background:"linear-gradient(135deg,#132331,#293c4b)",fontSize:"54px",fontWeight:950,color:colors.yellow,letterSpacing:"-6px"},
  description:{color:"#c8d0dc",lineHeight:1.55,fontSize:"13px"},
  meta:{display:"grid",gap:"9px",fontSize:"12px",color:colors.muted},
  metaLine:{display:"flex",justifyContent:"space-between",gap:"14px"},
  tags:{display:"flex",flexWrap:"wrap",gap:"6px"},
  tag:{padding:"5px 7px",borderRadius:"5px",backgroundColor:colors.raised,color:"#aeb9c8",fontSize:"10px",fontWeight:750},
  relatedGrid:{display:"grid",gridTemplateColumns:"64px 1fr",gap:"10px",alignItems:"center",padding:"9px 0",borderBottom:"1px solid",borderColor:"#202b3a"},
  thumb:{width:"64px",height:"48px",display:"grid",placeItems:"center",borderRadius:"6px",fontWeight:950,fontSize:"16px"},
  social:{marginTop:"18px"},
  actionRow:{display:"flex",gap:"8px",flexWrap:"wrap",padding:"12px",borderBottom:"1px solid",borderColor:colors.line},
  action:{border:"1px solid",borderColor:colors.line,borderRadius:"7px",backgroundColor:colors.raised,color:colors.text,padding:"8px 11px",fontSize:"12px",fontWeight:800,cursor:"pointer"},
  commentForm:{display:"flex",gap:"8px",padding:"14px"},
  input:{flex:1,minWidth:0,backgroundColor:"#0b1017",border:"1px solid",borderColor:colors.line,color:colors.text,borderRadius:"7px",padding:"10px 12px"},
  comments:{display:"grid",gap:"1px",backgroundColor:colors.line},
  comment:{padding:"14px",backgroundColor:colors.panel},
  commentHead:{display:"flex",justifyContent:"space-between",fontSize:"11px",fontWeight:900,color:colors.blue},
  commentBody:{margin:"7px 0 0",fontSize:"13px",lineHeight:1.5,color:"#d5dbe4"},
  footer:{padding:"38px 0 0",color:colors.muted,fontSize:"11px",display:"flex",justifyContent:"space-between",gap:"20px"}
});
